# https://github.com/felt/ultimate-elixir-ci/blob/main/.github/workflows/elixir-build-and-test.yml
# Used under MIT License: https://github.com/felt/ultimate-elixir-ci/blob/main/LICENSE

name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    strategy:
      matrix:
        elixir: ["1.17.2"]
        otp: ["27.0.1"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Elixir Project
        uses: ./.github/actions/elixir-setup
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
          # build-flags: --all-warnings --warnings-as-errors
          build-flags: --all-warnings

      - name: Run Tests
        run: mix test
        if: always()

      # Optional, but Codecov has a bot that will comment on your PR with per-file
      # coverage deltas. Use mix coveralls.json above
      # - name: Upload to Codecov
      #  uses: codecov/codecov-action@v1
      #  with:
      #    token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
      #    files: ./cover/excoveralls.json
